In [1]:
!pip install pyspark

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/pyspark/
Collecting pyspark
  Downloading pyspark-3.5.0.tar.gz (316.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.9/316.9 MB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.0-py2.py3-none-any.whl size=317425345 sha256=fe20f86380a248369ee3db4825d23494bd763b2183a82ee59f7db2878dbf2a07
  Stored in directory: /root/.cache/pip/wheels/41/4e/10/c2cf2467f71c678cfc8a6b9ac9241e5e44a01940da8fbb17fc
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.0

In [2]:
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

## Consultas e seleçoes

In [3]:
df = spark.sql('''select 'OK' as status''')
df.show()

+------+
|status|
+------+
|    OK|
+------+

## Importando dados

In [4]:
df = spark.read.csv('/content/drive/MyDrive/FIAP/Fase 03/cereal.csv', sep = ',', inferSchema= True, header = True)
df.show()

+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
|                name|mfr|type|calories|protein|fat|sodium|fiber|carbo|sugars|potass|vitamins|shelf|weight|cups|   rating|
+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
|           100% Bran|  N|   C|      70|      4|  1|   130| 10.0|  5.0|     6|   280|      25|    3|   1.0|0.33|68.402973|
|   100% Natural Bran|  Q|   C|     120|      3|  5|    15|  2.0|  8.0|     8|   135|       0|    3|   1.0| 1.0|33.983679|
|            All-Bran|  K|   C|      70|      4|  1|   260|  9.0|  7.0|     5|   320|      25|    3|   1.0|0.33|59.425505|
|All-Bran with Ext...|  K|   C|      50|      4|  0|   140| 14.0|  8.0|     0|   330|      25|    3|   1.0| 0.5|93.704912|
|      Almond Delight|  R|   C|     110|      2|  2|   200|  1.0| 14.0|     8|    -1|      25|    3|   1.0|0.75|34.384843|
|Apple Cinnamon Ch...|  G|   C|     110|      2|  2|   180|  1.5| 10.5|    10|    70|      25|    1|   1.0|0.75|29.509541|
|         Apple Jacks|  K|   C|     110|      2|  0|   125|  1.0| 11.0|    14|    30|      25|    2|   1.0| 1.0|33.174094|
|             Basic 4|  G|   C|     130|      3|  2|   210|  2.0| 18.0|     8|   100|      25|    3|  1.33|0.75|37.038562|
|           Bran Chex|  R|   C|      90|      2|  1|   200|  4.0| 15.0|     6|   125|      25|    1|   1.0|0.67|49.120253|
|         Bran Flakes|  P|   C|      90|      3|  0|   210|  5.0| 13.0|     5|   190|      25|    3|   1.0|0.67|53.313813|
|        Cap'n'Crunch|  Q|   C|     120|      1|  2|   220|  0.0| 12.0|    12|    35|      25|    2|   1.0|0.75|18.042851|
|            Cheerios|  G|   C|     110|      6|  2|   290|  2.0| 17.0|     1|   105|      25|    1|   1.0|1.25|50.764999|
|Cinnamon Toast Cr...|  G|   C|     120|      1|  3|   210|  0.0| 13.0|     9|    45|      25|    2|   1.0|0.75|19.823573|
|            Clusters|  G|   C|     110|      3|  2|   140|  2.0| 13.0|     7|   105|      25|    3|   1.0| 0.5|40.400208|
|         Cocoa Puffs|  G|   C|     110|      1|  1|   180|  0.0| 12.0|    13|    55|      25|    2|   1.0| 1.0|22.736446|
|           Corn Chex|  R|   C|     110|      2|  0|   280|  0.0| 22.0|     3|    25|      25|    1|   1.0| 1.0|41.445019|
|         Corn Flakes|  K|   C|     100|      2|  0|   290|  1.0| 21.0|     2|    35|      25|    1|   1.0| 1.0|45.863324|
|           Corn Pops|  K|   C|     110|      1|  0|    90|  1.0| 13.0|    12|    20|      25|    2|   1.0| 1.0|35.782791|
|       Count Chocula|  G|   C|     110|      1|  1|   180|  0.0| 12.0|    13|    65|      25|    2|   1.0| 1.0|22.396513|
|  Cracklin' Oat Bran|  K|   C|     110|      3|  3|   140|  4.0| 10.0|     7|   160|      25|    3|   1.0| 0.5|40.448772|
+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
only showing top 20 rows

In [5]:
df.count()

77

## Manipulanção de dados com spark sql

In [6]:
df.createOrReplaceTempView("cereal")

In [7]:
cereal = spark.sql('''SELECT * FROM cereal WHERE type = 'C'  ''')
cereal.show()

+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
|                name|mfr|type|calories|protein|fat|sodium|fiber|carbo|sugars|potass|vitamins|shelf|weight|cups|   rating|
+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
|           100% Bran|  N|   C|      70|      4|  1|   130| 10.0|  5.0|     6|   280|      25|    3|   1.0|0.33|68.402973|
|   100% Natural Bran|  Q|   C|     120|      3|  5|    15|  2.0|  8.0|     8|   135|       0|    3|   1.0| 1.0|33.983679|
|            All-Bran|  K|   C|      70|      4|  1|   260|  9.0|  7.0|     5|   320|      25|    3|   1.0|0.33|59.425505|
|All-Bran with Ext...|  K|   C|      50|      4|  0|   140| 14.0|  8.0|     0|   330|      25|    3|   1.0| 0.5|93.704912|
|      Almond Delight|  R|   C|     110|      2|  2|   200|  1.0| 14.0|     8|    -1|      25|    3|   1.0|0.75|34.384843|
|Apple Cinnamon Ch...|  G|   C|     110|      2|  2|   180|  1.5| 10.5|    10|    70|      25|    1|   1.0|0.75|29.509541|
|         Apple Jacks|  K|   C|     110|      2|  0|   125|  1.0| 11.0|    14|    30|      25|    2|   1.0| 1.0|33.174094|
|             Basic 4|  G|   C|     130|      3|  2|   210|  2.0| 18.0|     8|   100|      25|    3|  1.33|0.75|37.038562|
|           Bran Chex|  R|   C|      90|      2|  1|   200|  4.0| 15.0|     6|   125|      25|    1|   1.0|0.67|49.120253|
|         Bran Flakes|  P|   C|      90|      3|  0|   210|  5.0| 13.0|     5|   190|      25|    3|   1.0|0.67|53.313813|
|        Cap'n'Crunch|  Q|   C|     120|      1|  2|   220|  0.0| 12.0|    12|    35|      25|    2|   1.0|0.75|18.042851|
|            Cheerios|  G|   C|     110|      6|  2|   290|  2.0| 17.0|     1|   105|      25|    1|   1.0|1.25|50.764999|
|Cinnamon Toast Cr...|  G|   C|     120|      1|  3|   210|  0.0| 13.0|     9|    45|      25|    2|   1.0|0.75|19.823573|
|            Clusters|  G|   C|     110|      3|  2|   140|  2.0| 13.0|     7|   105|      25|    3|   1.0| 0.5|40.400208|
|         Cocoa Puffs|  G|   C|     110|      1|  1|   180|  0.0| 12.0|    13|    55|      25|    2|   1.0| 1.0|22.736446|
|           Corn Chex|  R|   C|     110|      2|  0|   280|  0.0| 22.0|     3|    25|      25|    1|   1.0| 1.0|41.445019|
|         Corn Flakes|  K|   C|     100|      2|  0|   290|  1.0| 21.0|     2|    35|      25|    1|   1.0| 1.0|45.863324|
|           Corn Pops|  K|   C|     110|      1|  0|    90|  1.0| 13.0|    12|    20|      25|    2|   1.0| 1.0|35.782791|
|       Count Chocula|  G|   C|     110|      1|  1|   180|  0.0| 12.0|    13|    65|      25|    2|   1.0| 1.0|22.396513|
|  Cracklin' Oat Bran|  K|   C|     110|      3|  3|   140|  4.0| 10.0|     7|   160|      25|    3|   1.0| 0.5|40.448772|
+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
only showing top 20 rows

In [8]:
df2 = df.where(df['type'] == 'C')
df2.count()

74

In [9]:
df.where(df['mfr'] == 'G').show()

+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
|                name|mfr|type|calories|protein|fat|sodium|fiber|carbo|sugars|potass|vitamins|shelf|weight|cups|   rating|
+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
|Apple Cinnamon Ch...|  G|   C|     110|      2|  2|   180|  1.5| 10.5|    10|    70|      25|    1|   1.0|0.75|29.509541|
|             Basic 4|  G|   C|     130|      3|  2|   210|  2.0| 18.0|     8|   100|      25|    3|  1.33|0.75|37.038562|
|            Cheerios|  G|   C|     110|      6|  2|   290|  2.0| 17.0|     1|   105|      25|    1|   1.0|1.25|50.764999|
|Cinnamon Toast Cr...|  G|   C|     120|      1|  3|   210|  0.0| 13.0|     9|    45|      25|    2|   1.0|0.75|19.823573|
|            Clusters|  G|   C|     110|      3|  2|   140|  2.0| 13.0|     7|   105|      25|    3|   1.0| 0.5|40.400208|
|         Cocoa Puffs|  G|   C|     110|      1|  1|   180|  0.0| 12.0|    13|    55|      25|    2|   1.0| 1.0|22.736446|
|       Count Chocula|  G|   C|     110|      1|  1|   180|  0.0| 12.0|    13|    65|      25|    2|   1.0| 1.0|22.396513|
|Crispy Wheat & Ra...|  G|   C|     100|      2|  1|   140|  2.0| 11.0|    10|   120|      25|    3|   1.0|0.75|36.176196|
|      Golden Grahams|  G|   C|     110|      1|  1|   280|  0.0| 15.0|     9|    45|      25|    2|   1.0|0.75|23.804043|
|  Honey Nut Cheerios|  G|   C|     110|      3|  1|   250|  1.5| 11.5|    10|    90|      25|    1|   1.0|0.75|31.072217|
|                 Kix|  G|   C|     110|      2|  1|   260|  0.0| 21.0|     3|    40|      25|    2|   1.0| 1.5|39.241114|
|        Lucky Charms|  G|   C|     110|      2|  1|   180|  0.0| 12.0|    12|    55|      25|    2|   1.0| 1.0|26.734515|
|Multi-Grain Cheerios|  G|   C|     100|      2|  1|   220|  2.0| 15.0|     6|    90|      25|    1|   1.0| 1.0|40.105965|
|Oatmeal Raisin Crisp|  G|   C|     130|      3|  2|   170|  1.5| 13.5|    10|   120|      25|    3|  1.25| 0.5|30.450843|
|     Raisin Nut Bran|  G|   C|     100|      3|  2|   140|  2.5| 10.5|     8|   140|      25|    3|   1.0| 0.5|  39.7034|
|   Total Corn Flakes|  G|   C|     110|      2|  1|   200|  0.0| 21.0|     3|    35|     100|    3|   1.0| 1.0|38.839746|
|   Total Raisin Bran|  G|   C|     140|      3|  1|   190|  4.0| 15.0|    14|   230|     100|    3|   1.5| 1.0|28.592785|
|   Total Whole Grain|  G|   C|     100|      3|  1|   200|  3.0| 16.0|     3|   110|     100|    3|   1.0| 1.0|46.658844|
|             Triples|  G|   C|     110|      2|  1|   250|  0.0| 21.0|     3|    60|      25|    3|   1.0|0.75|39.106174|
|                Trix|  G|   C|     110|      1|  1|   140|  0.0| 13.0|    12|    25|      25|    2|   1.0| 1.0|27.753301|
+--------------------+---+----+--------+-------+---+------+-----+-----+------+------+--------+-----+------+----+---------+
only showing top 20 rows

##Select Distinct no SparkSQL

In [10]:
df.printSchema()

root
 |-- name: string (nullable = true)
 |-- mfr: string (nullable = true)
 |-- type: string (nullable = true)
 |-- calories: integer (nullable = true)
 |-- protein: integer (nullable = true)
 |-- fat: integer (nullable = true)
 |-- sodium: integer (nullable = true)
 |-- fiber: double (nullable = true)
 |-- carbo: double (nullable = true)
 |-- sugars: integer (nullable = true)
 |-- potass: integer (nullable = true)
 |-- vitamins: integer (nullable = true)
 |-- shelf: integer (nullable = true)
 |-- weight: double (nullable = true)
 |-- cups: double (nullable = true)
 |-- rating: double (nullable = true)

In [11]:
#DISTINCT usado para dropar repeticoes
cereal = spark.sql(''' SELECT DISTINCT type, mfr FROM cereal ''')
cereal.show()

+----+---+
|type|mfr|
+----+---+
|   C|  P|
|   C|  Q|
|   C|  N|
|   H|  Q|
|   C|  R|
|   H|  N|
|   C|  G|
|   H|  A|
|   C|  K|
+----+---+

#WHERE no SparkSQL

In [12]:
cereal = spark.sql(''' SELECT * FROM cereal WHERE mfr = 'K' ''')
cereal.count()

23

In [13]:
cereal = spark.sql(''' SELECT * FROM cereal WHERE calories = 100 ''')
cereal.count()

17

In [14]:
cereal = spark.sql(''' SELECT * FROM cereal WHERE mfr = 'K' AND calories = 100 ''')
cereal.count()

3

## GROUP BY

In [15]:
cereal = spark.sql(''' SELECT mfr, \
                              type, \
                              count(*) AS total, \
                              sum(calories) as total_calories \
                        FROM cereal \
                        GROUP BY \
                              mfr,\
                              type ''')
cereal.show()

+---+----+-----+--------------+
|mfr|type|total|total_calories|
+---+----+-----+--------------+
|  A|   H|    1|           100|
|  P|   C|    9|           980|
|  K|   C|   23|          2500|
|  G|   C|   22|          2450|
|  Q|   C|    7|           660|
|  R|   C|    8|           920|
|  Q|   H|    1|           100|
|  N|   H|    1|           100|
|  N|   C|    5|           420|
+---+----+-----+--------------+

## CASE WHEN

In [16]:
cereal = spark.sql(''' SELECT DISTINCT type \
                              FROM cereal''')
cereal.show()

+----+
|type|
+----+
|   C|
|   H|
+----+

In [17]:
# Comentario em sql --
cereal = spark.sql(''' SELECT mfr,
                              type,
                              (case
                                    when type = 'C' then 'A'
                                    when type = 'H' then 'B'
                                    else 'C'
                              end) as type_new, \
                              count(*) AS total, \
                              sum(calories) as total_calories \
                        FROM cereal \
                        GROUP BY \
                              mfr,\
                              type ''')
cereal.show()

+---+----+--------+-----+--------------+
|mfr|type|type_new|total|total_calories|
+---+----+--------+-----+--------------+
|  A|   H|       B|    1|           100|
|  P|   C|       A|    9|           980|
|  K|   C|       A|   23|          2500|
|  G|   C|       A|   22|          2450|
|  Q|   C|       A|    7|           660|
|  R|   C|       A|    8|           920|
|  Q|   H|       B|    1|           100|
|  N|   H|       B|    1|           100|
|  N|   C|       A|    5|           420|
+---+----+--------+-----+--------------+

# consultas avançadas em SQL usando pyspark

In [18]:
cereal = spark.sql('''
                  SELECT mfr,
                         type,

                         sum(calories) as sum_calories,
                         min(calories) as min_calories,
                         max(calories) as max_calories,
                         cast(avg(calories) as decimal(10,2)) as avg_calories,

                         sum(carbo) as sum_carbo,
                         min(carbo) as min_carbo,
                         max(carbo) as max_carbo,
                         cast(avg(carbo) as decimal(10,2)) as avg_carbo,

                         sum(vitamins) as sum_vitamins,
                         min(vitamins) as min_vitamins,
                         max(vitamins) as max_vitamins,
                         cast(avg(vitamins) as decimal(10,2)) as avg_vitamins,

                         count(distinct name) as count_distinctive_names,
                         count(name) as count_names
                  FROM cereal
                  GROUP BY mfr, type
                  ORDER BY mfr, type
                   ''')
cereal.show()

+---+----+------------+------------+------------+------------+---------+---------+---------+---------+------------+------------+------------+------------+-----------------------+-----------+
|mfr|type|sum_calories|min_calories|max_calories|avg_calories|sum_carbo|min_carbo|max_carbo|avg_carbo|sum_vitamins|min_vitamins|max_vitamins|avg_vitamins|count_distinctive_names|count_names|
+---+----+------------+------------+------------+------------+---------+---------+---------+---------+------------+------------+------------+------------+-----------------------+-----------+
|  A|   H|         100|         100|         100|      100.00|     16.0|     16.0|     16.0|    16.00|          25|          25|          25|       25.00|                      1|          1|
|  G|   C|        2450|         100|         140|      111.36|    324.0|     10.5|     21.0|    14.73|         775|          25|         100|       35.23|                     22|         22|
|  K|   C|        2500|          50|         160|      108.70|    348.0|      7.0|     22.0|    15.13|         800|          25|         100|       34.78|                     23|         23|
|  N|   C|         420|          70|          90|       84.00|     75.0|      5.0|     20.0|    15.00|          50|           0|          25|       10.00|                      5|          5|
|  N|   H|         100|         100|         100|      100.00|     21.0|     21.0|     21.0|    21.00|           0|           0|           0|        0.00|                      1|          1|
|  P|   C|         980|          90|         120|      108.89|    119.0|     11.0|     17.0|    13.22|         225|          25|          25|       25.00|                      9|          9|
|  Q|   C|         660|          50|         120|       94.29|     81.0|      8.0|     14.0|    11.57|         100|           0|          25|       14.29|                      7|          7|
|  Q|   H|         100|         100|         100|      100.00|     -1.0|     -1.0|     -1.0|    -1.00|           0|           0|           0|        0.00|                      1|          1|
|  R|   C|         920|          90|         150|      115.00|    141.0|     14.0|     23.0|    17.63|         200|          25|          25|       25.00|                      8|          8|
+---+----+------------+------------+------------+------------+---------+---------+---------+---------+------------+------------+------------+------------+-----------------------+-----------+

In [19]:
cereal = spark.sql('''
                  SELECT mfr,
                         type,
                         (case
                            when mfr = 'A' then 'Abacaxi'
                            when mfr = 'G' then 'Goiaba'
                            when mfr = 'K' then 'Banana'
                            when mfr = 'N' then 'Maça'
                            when mfr = 'P' then 'Tomate'
                            when mfr = 'Q' then 'Pera'
                            when mfr = 'R' then 'Uva'
                            else 'NA'
                         end) as type_fuit,

                         sum(calories) as sum_calories,
                         min(calories) as min_calories,
                         max(calories) as max_calories,
                         cast(avg(calories) as decimal(10,2)) as avg_calories,

                         sum(carbo) as sum_carbo,
                         min(carbo) as min_carbo,
                         max(carbo) as max_carbo,
                         cast(avg(carbo) as decimal(10,2)) as avg_carbo,

                         sum(vitamins) as sum_vitamins,
                         min(vitamins) as min_vitamins,
                         max(vitamins) as max_vitamins,
                         cast(avg(vitamins) as decimal(10,2)) as avg_vitamins,

                         count(distinct name) as count_distinctive_names,
                         count(name) as count_names
                  FROM cereal
                  GROUP BY mfr, type
                  ORDER BY mfr, type
                   ''')
cereal.show()

+---+----+---------+------------+------------+------------+------------+---------+---------+---------+---------+------------+------------+------------+------------+-----------------------+-----------+
|mfr|type|type_fuit|sum_calories|min_calories|max_calories|avg_calories|sum_carbo|min_carbo|max_carbo|avg_carbo|sum_vitamins|min_vitamins|max_vitamins|avg_vitamins|count_distinctive_names|count_names|
+---+----+---------+------------+------------+------------+------------+---------+---------+---------+---------+------------+------------+------------+------------+-----------------------+-----------+
|  A|   H|  Abacaxi|         100|         100|         100|      100.00|     16.0|     16.0|     16.0|    16.00|          25|          25|          25|       25.00|                      1|          1|
|  G|   C|   Goiaba|        2450|         100|         140|      111.36|    324.0|     10.5|     21.0|    14.73|         775|          25|         100|       35.23|                     22|         22|
|  K|   C|   Banana|        2500|          50|         160|      108.70|    348.0|      7.0|     22.0|    15.13|         800|          25|         100|       34.78|                     23|         23|
|  N|   C|     Maça|         420|          70|          90|       84.00|     75.0|      5.0|     20.0|    15.00|          50|           0|          25|       10.00|                      5|          5|
|  N|   H|     Maça|         100|         100|         100|      100.00|     21.0|     21.0|     21.0|    21.00|           0|           0|           0|        0.00|                      1|          1|
|  P|   C|   Tomate|         980|          90|         120|      108.89|    119.0|     11.0|     17.0|    13.22|         225|          25|          25|       25.00|                      9|          9|
|  Q|   C|     Pera|         660|          50|         120|       94.29|     81.0|      8.0|     14.0|    11.57|         100|           0|          25|       14.29|                      7|          7|
|  Q|   H|     Pera|         100|         100|         100|      100.00|     -1.0|     -1.0|     -1.0|    -1.00|           0|           0|           0|        0.00|                      1|          1|
|  R|   C|      Uva|         920|          90|         150|      115.00|    141.0|     14.0|     23.0|    17.63|         200|          25|          25|       25.00|                      8|          8|
+---+----+---------+------------+------------+------------+------------+---------+---------+---------+---------+------------+------------+------------+------------+-----------------------+-----------+

#JOINs

##INNER

In [21]:
sales = spark.read.csv('/content/drive/MyDrive/FIAP/Fase 03/sales_data_sample.csv', sep = ',', inferSchema= True, header = True)

In [30]:
sales.show(5)

+-----------+---------------+---------+---------------+-------+---------------+-------+------+--------+-------+-----------+----+-----------+--------------------+----------------+--------------------+------------+-------------+-----+----------+-------+---------+---------------+----------------+--------+
|ORDERNUMBER|QUANTITYORDERED|PRICEEACH|ORDERLINENUMBER|  SALES|      ORDERDATE| STATUS|QTR_ID|MONTH_ID|YEAR_ID|PRODUCTLINE|MSRP|PRODUCTCODE|        CUSTOMERNAME|           PHONE|        ADDRESSLINE1|ADDRESSLINE2|         CITY|STATE|POSTALCODE|COUNTRY|TERRITORY|CONTACTLASTNAME|CONTACTFIRSTNAME|DEALSIZE|
+-----------+---------------+---------+---------------+-------+---------------+-------+------+--------+-------+-----------+----+-----------+--------------------+----------------+--------------------+------------+-------------+-----+----------+-------+---------+---------------+----------------+--------+
|      10107|             30|     95.7|              2| 2871.0| 2/24/2003 0:00|Shipped|     1|       2|   2003|Motorcycles|  95|   S10_1678|   Land of Toys Inc.|      2125557818|897 Long Airport ...|        NULL|          NYC|   NY|     10022|    USA|       NA|             Yu|            Kwai|   Small|
|      10121|             34|    81.35|              5| 2765.9|  5/7/2003 0:00|Shipped|     2|       5|   2003|Motorcycles|  95|   S10_1678|  Reims Collectables|      26.47.1555|  59 rue de l'Abbaye|        NULL|        Reims| NULL|     51100| France|     EMEA|        Henriot|            Paul|   Small|
|      10134|             41|    94.74|              2|3884.34|  7/1/2003 0:00|Shipped|     3|       7|   2003|Motorcycles|  95|   S10_1678|     Lyon Souveniers|+33 1 46 62 7555|27 rue du Colonel...|        NULL|        Paris| NULL|     75508| France|     EMEA|       Da Cunha|          Daniel|  Medium|
|      10145|             45|    83.26|              6| 3746.7| 8/25/2003 0:00|Shipped|     3|       8|   2003|Motorcycles|  95|   S10_1678|   Toys4GrownUps.com|      6265557265|  78934 Hillside Dr.|        NULL|     Pasadena|   CA|     90003|    USA|       NA|          Young|           Julie|  Medium|
|      10159|             49|    100.0|             14|5205.27|10/10/2003 0:00|Shipped|     4|      10|   2003|Motorcycles|  95|   S10_1678|Corporate Gift Id...|      6505551386|     7734 Strong St.|        NULL|San Francisco|   CA|      NULL|    USA|       NA|          Brown|           Julie|  Medium|
+-----------+---------------+---------+---------------+-------+---------------+-------+------+--------+-------+-----------+----+-----------+--------------------+----------------+--------------------+------------+-------------+-----+----------+-------+---------+---------------+----------------+--------+
only showing top 5 rows

In [27]:
sales.printSchema()

root
 |-- ORDERNUMBER: integer (nullable = true)
 |-- QUANTITYORDERED: integer (nullable = true)
 |-- PRICEEACH: double (nullable = true)
 |-- ORDERLINENUMBER: integer (nullable = true)
 |-- SALES: double (nullable = true)
 |-- ORDERDATE: string (nullable = true)
 |-- STATUS: string (nullable = true)
 |-- QTR_ID: integer (nullable = true)
 |-- MONTH_ID: integer (nullable = true)
 |-- YEAR_ID: integer (nullable = true)
 |-- PRODUCTLINE: string (nullable = true)
 |-- MSRP: integer (nullable = true)
 |-- PRODUCTCODE: string (nullable = true)
 |-- CUSTOMERNAME: string (nullable = true)
 |-- PHONE: string (nullable = true)
 |-- ADDRESSLINE1: string (nullable = true)
 |-- ADDRESSLINE2: string (nullable = true)
 |-- CITY: string (nullable = true)
 |-- STATE: string (nullable = true)
 |-- POSTALCODE: string (nullable = true)
 |-- COUNTRY: string (nullable = true)
 |-- TERRITORY: string (nullable = true)
 |-- CONTACTLASTNAME: string (nullable = true)
 |-- CONTACTFIRSTNAME: string (nullable = true)
 |-- DEALSIZE: string (nullable = true)

In [24]:
sales.createOrReplaceTempView('sales')

In [37]:
calendar = spark.sql('''
                  SELECT DISTINCT orderdate, qtr_id, month_id, year_id
                  FROM sales
                  ORDER BY orderdate
                  ''')
sales_data = spark.sql('''
                  SELECT DISTINCT ORDERNUMBER,
                                  CUSTOMERNAME,
                                  ORDERDATE,
                                  SALES,
                                  QUANTITYORDERED,
                                  PRODUCTCODE,
                                  ORDERLINENUMBER,
                                  PRICEEACH
                  FROM sales
                  ORDER BY ORDERNUMBER
                  ''')

customers = spark.sql('''
                  SELECT DISTINCT CUSTOMERNAME,
                                  PHONE,
                                  ADDRESSLINE1,
                                  ADDRESSLINE2,
                                  CITY,
                                  STATE,
                                  POSTALCODE,
                                  COUNTRY,
                                  TERRITORY
                  FROM sales
                  ORDER BY CUSTOMERNAME
                  ''')

sales_data.createOrReplaceTempView('sales_data')
calendar.createOrReplaceTempView('calendar')
customers.createOrReplaceTempView('customers')

In [33]:
calendar.count()

252

In [34]:
sales_data.count()

2823

In [35]:
customers.count()

92

In [39]:
master = spark.sql('''

                    SELECT *
                    FROM sales_data s
                    INNER JOIN customers c ON s.CUSTOMERNAME = c.CUSTOMERNAME

                  ''')
master.show()

+-----------+--------------------+---------------+-------+---------------+-----------+---------------+---------+--------------------+---------------+--------------------+------------+-----------+-----+----------+---------+---------+
|ORDERNUMBER|        CUSTOMERNAME|      ORDERDATE|  SALES|QUANTITYORDERED|PRODUCTCODE|ORDERLINENUMBER|PRICEEACH|        CUSTOMERNAME|          PHONE|        ADDRESSLINE1|ADDRESSLINE2|       CITY|STATE|POSTALCODE|  COUNTRY|TERRITORY|
+-----------+--------------------+---------------+-------+---------------+-----------+---------------+---------+--------------------+---------------+--------------------+------------+-----------+-----+----------+---------+---------+
|      10275|   La Rochelle Gifts| 7/23/2004 0:00|4177.35|             45|   S10_1678|              1|    92.83|   La Rochelle Gifts|     40.67.8555|67, rue des Cinqu...|        NULL|     Nantes| NULL|     44000|   France|     EMEA|
|      10291|Scandinavian Gift...|  9/8/2004 0:00|7136.19|             37|   S10_1949|             11|    100.0|Scandinavian Gift...|   0695-34 6555|        ?kergatan 24|        NULL|      Boras| NULL|  S-844 67|   Sweden|     EMEA|
|      10382|Mini Gifts Distri...| 2/17/2005 0:00|4071.85|             37|   S12_3148|             11|    100.0|Mini Gifts Distri...|     4155551450|     5677 Strong St.|        NULL| San Rafael|   CA|     97562|      USA|       NA|
|      10278|  Signal Gift Stores|  8/6/2004 0:00|4667.86|             34|   S18_1129|              6|    100.0|  Signal Gift Stores|     7025551838|     8489 Strong St.|        NULL|  Las Vegas|   NV|     83030|      USA|       NA|
|      10207|Diecast Collectables| 12/9/2003 0:00|7060.24|             44|   S18_2238|              6|    100.0|Diecast Collectables|     6175552555|      6251 Ingle Ln.|        NULL|     Boston|   MA|     51003|      USA|       NA|
|      10246|Euro Shopping Cha...|  5/5/2004 0:00| 6549.2|             40|   S18_2238|              4|    100.0|Euro Shopping Cha...| (91) 555 94 44|  C/ Moralzarzal, 86|        NULL|     Madrid| NULL|     28034|    Spain|     EMEA|
|      10184|Iberia Gift Impor...|11/14/2003 0:00|1863.41|             31|   S24_1444|              3|    60.11|Iberia Gift Impor...| (95) 555 82 82|       C/ Romero, 33|        NULL|    Sevilla| NULL|     41101|    Spain|     EMEA|
|      10407|The Sharp Gifts W...| 4/22/2005 0:00| 2576.0|             64|   S24_1628|             10|    40.25|The Sharp Gifts W...|     4085553659|      3086 Ingle Ln.|        NULL|   San Jose|   CA|     94217|      USA|       NA|
|      10324|     Vitachrome Inc.| 11/5/2004 0:00|3820.44|             31|   S24_2300|              2|    100.0|     Vitachrome Inc.|     2125551500|   2678 Kingston Rd.|   Suite 101|        NYC|   NY|     10022|      USA|       NA|
|      10394|Euro Shopping Cha...| 3/15/2005 0:00| 1789.4|             46|   S24_2840|              6|     38.9|Euro Shopping Cha...| (91) 555 94 44|  C/ Moralzarzal, 86|        NULL|     Madrid| NULL|     28034|    Spain|     EMEA|
|      10332|      AV Stores, Co.|11/17/2004 0:00|1859.44|             44|   S24_2887|             11|    42.26|      AV Stores, Co.| (171) 555-1555|   Fauntleroy Circus|        NULL| Manchester| NULL|   EC2 5NT|       UK|     EMEA|
|      10361|Souveniers And Th...|12/17/2004 0:00|3544.17|             49|   S32_4289|              2|    72.33|Souveniers And Th...|+61 2 9495 8555|Monitor Money Bui...|     Level 6|  Chatswood|  NSW|      2067|Australia|     APAC|
|      10375|   La Rochelle Gifts|  2/3/2005 0:00| 3224.2|             49|   S50_1341|              5|     65.8|   La Rochelle Gifts|     40.67.8555|67, rue des Cinqu...|        NULL|     Nantes| NULL|     44000|   France|     EMEA|
|      10383|Euro Shopping Cha...| 2/22/2005 0:00|3087.05|             29|   S50_1392|             13|    100.0|Euro Shopping Cha...| (91) 555 94 44|  C/ Moralzarzal, 86|        NULL|     Madrid| NULL|     28034|    Spain|     EMEA|
|      10135|Mini Gifts Distri...|  7/2/2003 0:00| 4224.0|             44|   S50_4713|             15|     96.0|Mini Gifts Distri...|     4155551450|     5677 Strong St.|        NULL| San Rafael|   CA|     97562|      USA|       NA|
|      10401|Tekni Collectable...|  4/3/2005 0:00|2018.31|             21|  S700_2834|              2|    96.11|Tekni Collectable...|     2015559350|       7476 Moss Rd.|        NULL|     Newark|   NJ|     94019|      USA|       NA|
|      10373|Oulu Toy Supplies...| 1/31/2005 0:00| 2502.9|             45|  S700_4002|             17|    55.62|Oulu Toy Supplies...|     981-443655|         Torikatu 38|        NULL|       Oulu| NULL|     90110|  Finland|     EMEA|
|      10209|Men 'R' US Retail...|  1/9/2004 0:00|2145.12|             48|   S72_1253|              3|    44.69|Men 'R' US Retail...|     2155554369|    6047 Douglas Av.|        NULL|Los Angeles|   CA|      NULL|      USA|       NA|
|      10292|   Land of Toys Inc.|  9/8/2004 0:00|4554.94|             26|   S18_2238|              7|    100.0|   Land of Toys Inc.|     2125557818|897 Long Airport ...|        NULL|        NYC|   NY|     10022|      USA|       NA|
|      10196|    Super Scale Inc.|11/26/2003 0:00|3564.75|             35|   S18_3259|              3|    100.0|    Super Scale Inc.|     2035559545|567 North Pendale...|        NULL|  New Haven|   CT|     97823|      USA|       NA|
+-----------+--------------------+---------------+-------+---------------+-----------+---------------+---------+--------------------+---------------+--------------------+------------+-----------+-----+----------+---------+---------+
only showing top 20 rows